### ISSUE TITLE
[Badges update]: Portfolio, website, blog, LinkedIn, Discord server

### ISSUE THREAD

**Issue by Nighty3098** [jasper-clarke/jasper-clarke#1]
<div align="center">

<h1>Hi 👋🏻</h1>

<img src="https://github.com/Nighty3098/DevIcons/blob/main/badges/badges_Portfolio.png?raw=true" height="50px" /> 
<br/>
<img src="https://github.com/Nighty3098/DevIcons/blob/main/badges/badges_LinkedIn_badge.png?raw=true" height="50px" />
<br/>
<img src="https://github.com/Nighty3098/DevIcons/blob/main/badges/badges_discord_server.png?raw=true" height="50px" />
<br/>
<img src="https://github.com/Nighty3098/DevIcons/blob/main/badges/badges_blog.png?raw=true" height="50px" /> 
<br/>
<img src="https://github.com/Nighty3098/DevIcons/blob/main/badges/badges_Site.png?raw=true" height="50px" /> 
<br/>

</div>

**Comment by jasper-clarke** [comment]
Thanks for that heads up @Nighty3098 
I've updated my readme with your awesome new icons!
